/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import metier.CategorieFilm;
import metier.CategorieMusique;
import metier.Film;
import static metier.Film.COMPARATOR_CAT;
import metier.TypeOeuvre;

/**
 *
 * @author johan
 */
public class Rechercher extends javax.swing.JFrame {

    /**
     * Creates new form Rechercher
     */
    public Rechercher() {
        cbBoxTypeOeuvreModele = new DefaultComboBoxModel(nomType);
        cbBoxTypeCategorieModele = new DefaultComboBoxModel(nomCatFilm);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRecherche = new javax.swing.JPanel();
        jLabelTitre = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jLabelCat = new javax.swing.JLabel();
        jLabelGroupe = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jComboBoxGroupe = new javax.swing.JComboBox<>();
        jTextFieldTitre = new javax.swing.JTextField();
        jPanelResultat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultat = new javax.swing.JTextArea();
        jButtonRecherche = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jButtonAfficher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelRecherche.setBorder(javax.swing.BorderFactory.createTitledBorder("Champs de recherche"));

        jLabelTitre.setText("Titre : ");

        jLabelType.setText("Type");

        jLabelCat.setText("Categorie");

        jLabelGroupe.setText("Groupe");

        jComboBoxType.setModel(cbBoxTypeOeuvreModele);
        jComboBoxType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTypeItemStateChanged(evt);
            }
        });

        jComboBoxCat.setModel(cbBoxTypeCategorieModele);

        jComboBoxGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGroupeActionPerformed(evt);
            }
        });

        jTextFieldTitre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRechercheLayout = new javax.swing.GroupLayout(jPanelRecherche);
        jPanelRecherche.setLayout(jPanelRechercheLayout);
        jPanelRechercheLayout.setHorizontalGroup(
            jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechercheLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRechercheLayout.createSequentialGroup()
                        .addComponent(jLabelTitre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTitre)
                        .addGap(73, 73, 73))
                    .addGroup(jPanelRechercheLayout.createSequentialGroup()
                        .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelType)
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCat)
                            .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGroupe)
                            .addComponent(jComboBoxGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(131, Short.MAX_VALUE))))
        );
        jPanelRechercheLayout.setVerticalGroup(
            jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRechercheLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitre)
                    .addComponent(jTextFieldTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelType)
                    .addComponent(jLabelCat)
                    .addComponent(jLabelGroupe))
                .addGap(18, 18, 18)
                .addGroup(jPanelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelResultat.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultat"));

        jTextAreaResultat.setColumns(20);
        jTextAreaResultat.setRows(5);
        jTextAreaResultat.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaResultat);

        javax.swing.GroupLayout jPanelResultatLayout = new javax.swing.GroupLayout(jPanelResultat);
        jPanelResultat.setLayout(jPanelResultatLayout);
        jPanelResultatLayout.setHorizontalGroup(
            jPanelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultatLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelResultatLayout.setVerticalGroup(
            jPanelResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultatLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonRecherche.setText("Rechercher");
        jButtonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercheActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jButtonAfficher.setText("Afficher");
        jButtonAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRecherche)
                .addGap(18, 18, 18)
                .addComponent(jButtonAfficher)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetour)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanelRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelResultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRecherche)
                    .addComponent(jButtonRetour)
                    .addComponent(jButtonAfficher))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGroupeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGroupeActionPerformed

    private void jComboBoxTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTypeItemStateChanged
        
        if(evt.getItem()=="Film"){
            cbBoxTypeCategorieModele = new DefaultComboBoxModel(nomCatFilm);
            jComboBoxCat.setModel(cbBoxTypeCategorieModele);
        }
        
        if(evt.getItem()=="Musique"){
            cbBoxTypeCategorieModele = new DefaultComboBoxModel(nomCatMusique);
            jComboBoxCat.setModel(cbBoxTypeCategorieModele);
        }
        if(evt.getItem()=="Ecrit"){
            
        }
        if(evt.getItem()=="Image"){
            
        }
        if(evt.getItem()=="Jeux"){
            
        }
        
        
    }//GEN-LAST:event_jComboBoxTypeItemStateChanged

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jTextFieldTitreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitreActionPerformed

    private void jButtonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercheActionPerformed
        
        listeFilmTrouve.clear();
        jTextAreaResultat.setText("");
        
        String str="";
        
        listeFilm.sort(COMPARATOR_CAT);
        
        Iterator<Film> iter = listeFilm.iterator();
        
        if((jTextFieldTitre.getText().equals(""))){ //Recherche par Type et Categorie
            //System.out.println("CAT");
           
            while(iter.hasNext()){
                
                Film f= iter.next();
                
                System.out.print(Film.getType().getNom());
                
                if(Film.getType().getNom().equals("Film") && f.getCategoriePrincipale().getNomCat().equals(jComboBoxCat.getSelectedItem())){
                    listeFilmTrouve.add(f);
                    jTextAreaResultat.append(f.getTitre()+"\n");
                }
                //Repéter le if à chaque categorie. Un peu long il doit y avoir meilleur ! 
                
            }
            
        }
        else { //Recherche par titre
           //System.out.println("TITRE");
           iter = listeFilm.iterator();
            
           while(iter.hasNext()){
                
               Film f = iter.next(); 
               
                if(f.getTitre().contains(jTextFieldTitre.getText())){
                    
                    System.out.println(f.getTitre());
                    listeFilmTrouve.add(f);
                    str = str+f.getTitre()+"\n";
                }   
        }
            jTextAreaResultat.setText(str);
        }
    }//GEN-LAST:event_jButtonRechercheActionPerformed

    private void jButtonAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherActionPerformed
        System.out.println(listeFilmTrouve.size());
        if(listeFilmTrouve.size()==1){
            AffichageFilm affiche = new AffichageFilm(this, true,listeFilmTrouve);
            affiche.setVisible(true);
        }
        else if(listeFilmTrouve.size()==0);
        else{ //Ne fonctionne pas !
            SelectionFilm select = new SelectionFilm(this, true,listeFilmTrouve);
            select.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAfficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rechercher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfficher;
    private javax.swing.JButton jButtonRecherche;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private javax.swing.JComboBox<String> jComboBoxGroupe;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabelCat;
    private javax.swing.JLabel jLabelGroupe;
    private javax.swing.JLabel jLabelTitre;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelRecherche;
    private javax.swing.JPanel jPanelResultat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResultat;
    private javax.swing.JTextField jTextFieldTitre;
    // End of variables declaration//GEN-END:variables
   
    //variable perso
    
    Object[] nomCatFilm=CategorieFilm.getCat().toArray();
    Object[] nomCatMusique=CategorieMusique.getCat().toArray();    
    Object[] nomType=TypeOeuvre.getListeOeuvre().toArray();
    
    private ComboBoxModel<String> cbBoxTypeOeuvreModele;
    private ComboBoxModel<String> cbBoxTypeCategorieModele;
    private ComboBoxModel<String> cbBoxTypeGroupeModele;
    
    
    private final ArrayList<Film> listeFilm= Film.getListeFilm();
    private ArrayList<Film> listeFilmTrouve = new ArrayList<>();

}
