/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Color;
import javax.swing.JOptionPane;
import static metier.CategorieEcrit.convertToEnumCategorieEcrit;
import static metier.CategorieFilm.convertToEnumCategorieFilm;
import static metier.CategorieMusiqueClip.convertToEnumCategorieClipMusique;
import metier.ClipVideo;
import metier.Ecrit;
import metier.Film;
import metier.Image;
import metier.JeuVideo;
import metier.Musique;
import metier.Oeuvre;
import static metier.Oeuvre.listeOeuvresGerees;
import metier.TypeOeuvre;

/**
 *
 * @author jo
 */
public class AffichageOeuvre extends javax.swing.JDialog {

    /**
     * Creates new form Test
     */
    public AffichageOeuvre(Oeuvre o)
    {
        
        initComponents();
        
        oeuvre = o;
        
        jButton4.setEnabled(false);                                          //bouton enregistrer modifs desactivé 
        
        double note = oeuvre.getNoteOeuvre() ;
        
        jLabel3.setText(oeuvre.getMetierArtisteOeuvre().getNomMetierArtiste());  //metier de l'artiste
        
        jTextField1.setText(oeuvre.getArtisteOeuvre().getNomArtiste());
        jTextField1.setEditable(false);        
        jTextField2.setText(oeuvre.getNomOeuvre());
        jTextField2.setEditable(false);
        jTextField4.setText(String.valueOf(oeuvre.getAnneeOeuvre()));            //necessité de convertir int en String
        jTextField4.setEditable(false);
        jTextField7.setText(oeuvre.getStatutOeuvre());
        jTextField7.setEditable(false);
        jTextField8.setText(oeuvre.getArtisteOeuvre().getNationaliteArtiste());
        jTextField8.setEditable(false);
        jTextField9.setText(String.valueOf(oeuvre.getIdOeuvre()));
        jTextField9.setEditable(false);
        jTextField11.setText(oeuvre.getTypeOeuvre().getNomTypeOeuvre());
        jTextField11.setEditable(false);
        jTextField12.setText(String.valueOf(oeuvre.getAgeMiniOeuvre()));
        jTextField12.setEditable(false);
        jTextField13.setText(String.format(java.util.Locale.US,"%.1f", note));   //1 chiffre après la virgule
        jTextField13.setEditable(false);

        
        if(o.getTypeOeuvre() == TypeOeuvre.ECR)
        {
            ecrit = (Ecrit)o;
            
            jTextField3.setEnabled(false);                                          //deuxieme categorie desactivée
            
            jLabel4.setText("Nombre de pages:");                                    //label Duree remplacée par Nombres de pages
            jTextField5.setText(String.valueOf(ecrit.getNombrePagesEcrit()));       //nb de pages
            
            jLabel6.setText("Categorie d'ecrit:");
            jTextField6.setText(ecrit.getCategorieEcrit().getNomCategorieEcrit());
            
            jLabel7.setEnabled(false);                                              //champ categorie secondaire desactivé
        }

        if(o.getTypeOeuvre() == TypeOeuvre.FLM)
        {        
            film = (Film)o;

            jTextField3.setText(film.getCategorieSecondaireDufilm().getNomCategorieFilm());
            jTextField3.setEditable(false);
            jTextField5.setText(String.valueOf(film.getDureeFilm()));
            jTextField5.setEditable(false);
            jTextField6.setText(film.getCategoriePrincipaleDuFilm().getNomCategorieFilm());
            jTextField6.setEditable(false);
            jTextField10.setText(String.valueOf(film.getIdFilm()));
            jTextField10.setEditable(false); 
        }
        
        if(o.getTypeOeuvre() == TypeOeuvre.CVO)
        {
            clip = (ClipVideo)o;
            
            jTextField3.setText(clip.getCategorieSecondaireMusique().getNomCategorieClipMusique());
            jTextField3.setEditable(false);
            jTextField5.setText(String.valueOf(clip.getDureeMusique()));
            jTextField5.setEditable(false);
            jTextField6.setText(clip.getCategoriePrincipaleMusique().getNomCategorieClipMusique());
            jTextField6.setEditable(false);
            jTextField10.setText(String.valueOf(clip.getIdClip()));
            jTextField10.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Réalisateur:");

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Durée (en min):");

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Année:");

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Catégorie principale:");

        jLabel7.setText("Catégorie secondaire:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Titre:");

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Statut:");

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("Fermer");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Nationalité:");

        jLabel10.setText("ID oeuvre:");

        jTextField9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Age minimum (en années):");

        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel12.setText("Type d'oeuvre:");

        jTextField11.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setText("ID type oeuvre:");

        jTextField12.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setText("Note moyenne:");
        jLabel14.setToolTipText("");

        jTextField13.setBackground(new java.awt.Color(204, 204, 204));

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Enregistrer les modifications");
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField9)
                            .addComponent(jTextField13))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jTextField6)
                            .addComponent(jTextField3)
                            .addComponent(jTextField7)
                            .addComponent(jTextField10)
                            .addComponent(jTextField12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/jo/Documents/DUT/Java/Netbeans/JoKeJo/JoKeJo/src/main/java/gif/pele_mele.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        //clic bouton Modifier
        jButton4.setEnabled(true);                              //bouton enregistrer modifs activé
        jTextField1.setEditable(true);
        jTextField1.setBackground(Color.white);
        jTextField2.setEditable(true);
        jTextField2.setBackground(Color.white);
        jTextField3.setEditable(true);
        jTextField3.setBackground(Color.white);
        jTextField4.setEditable(true);
        jTextField4.setBackground(Color.white);
        jTextField5.setEditable(true);
        jTextField5.setBackground(Color.white);
        jTextField6.setEditable(true);
        jTextField6.setBackground(Color.white);
        jTextField7.setEditable(true);
        jTextField7.setBackground(Color.white);
        jTextField8.setEditable(true);
        jTextField8.setBackground(Color.white);
        jTextField9.setEditable(false);                        //ID oeuvre non modifiable
        //jTextField9.setBackground(Color.white);
        jTextField10.setEditable(false);                       //ID type d'oeuvre non modifiable
        //jTextField10.setBackground(Color.white);
        jTextField11.setEditable(false);                        //type d'oeuvre non modifiable
        //jTextField11.setBackground(Color.white);
        jTextField12.setEditable(true);
        jTextField12.setBackground(Color.white);
        jTextField13.setEditable(false);                        //note non modifiable
        //jTextField13.setBackground(Color.white);
        
        jTextField2.requestFocus();                             //placer le curseur dans le premier textField
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
    {//GEN-HEADEREND:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField4ActionPerformed
    {//GEN-HEADEREND:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        String src = "Fonctionnalité en cours de développement";
        JOptionPane.showMessageDialog(this,src, "ERREUR",JOptionPane.INFORMATION_MESSAGE);
        
        /*for(Oeuvre oeuvre : listeOeuvresGerees)
        {
            if(oeuvre.getNomOeuvre().equalsIgnoreCase(jTextField2.getText().toString()))
                Oeuvre.supprimerOeuvre(oeuvre);
        }
        
        System.out.println(listeOeuvresGerees.toString());*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        //Enregistrer les modifications
        String src = "Fonctionnalité en cours de développement";
        JOptionPane.showMessageDialog(this,src, "ERREUR",JOptionPane.INFORMATION_MESSAGE);
        /*
        oeuvre.setTypeOeuvre(TypeOeuvre.convertStringToTypeOuvre(jTextField11.getText()));
        oeuvre.setNomOeuvre(jTextField2.getText());
        oeuvre.getArtisteOeuvre().setNomArtiste(jTextField1.getText());
        oeuvre.setAnneeOeuvre(Integer.parseInt(jTextField4.getText()));
        oeuvre.setNoteOeuvre(Integer.parseInt(jTextField12.getText()));
        oeuvre.getArtisteOeuvre().setNationaliteArtiste(jTextField8.getText());
        oeuvre.setStatutOeuvre(jTextField7.getText());
        
        TypeOeuvre type = oeuvre.getTypeOeuvre();

        switch(type){
            case FLM:
                film.setDureeFilm(Integer.parseInt(jTextField5.getText()));
                film.setCategoriePrincipale(convertToEnumCategorieFilm(jTextField6.getText()));
                film.setCategorieSecondaire(convertToEnumCategorieFilm(jTextField3.getText()));
                break;
            case MSQ:
                musique.setDureeMusique(Integer.parseInt(jTextField5.getText()));
                musique.setCategoriePrincipaleMusique(convertToEnumCategorieClipMusique(jTextField6.getText()));
                musique.setCategoriePrincipaleMusique(convertToEnumCategorieClipMusique(jTextField3.getText()));
                break;
            case ECR:
                ecrit.setNombrePagesEcrit(Integer.parseInt(jTextField5.getText()));
                ecrit.setCategorieEcrit(convertToEnumCategorieEcrit(jTextField6.getText()));
                break;
            default:
                System.out.println("Type oeuvre inconnu");
        }

        
        System.out.println(oeuvre.toString());              //verifier
        System.out.println(listeOeuvresGerees.toString());  //verifier */
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField10ActionPerformed
    {//GEN-HEADEREND:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AffichageOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AffichageOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AffichageOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AffichageOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                /*AffichageOeuvre dialog = new AffichageOeuvre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel2;
    javax.swing.JTextField jTextField1;
    javax.swing.JTextField jTextField10;
    javax.swing.JTextField jTextField11;
    javax.swing.JTextField jTextField12;
    javax.swing.JTextField jTextField13;
    javax.swing.JTextField jTextField2;
    javax.swing.JTextField jTextField3;
    javax.swing.JTextField jTextField4;
    javax.swing.JTextField jTextField5;
    javax.swing.JTextField jTextField6;
    javax.swing.JTextField jTextField7;
    javax.swing.JTextField jTextField8;
    javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
   
    
    
    private Film film;
    private ClipVideo clip;
    private Ecrit ecrit;
    private Oeuvre oeuvre;
    

}
