/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import metier.CategorieMusiqueClip;
import metier.CategorieFilm;
import metier.ClipVideo;
import static metier.ClipVideo.getNomsListeClips;
import static metier.ClipVideo.listeClipsGeres;
import metier.Ecrit;
import static metier.Ecrit.getNomsListeEcrits;
import static metier.Ecrit.listeEcritsGeres;
import metier.Film;
import static metier.Film.getNomsListeFilms;
import static metier.Film.listeFilmsGeres;
import metier.Image;
import static metier.Image.getNomsListeImages;
import static metier.Image.listeImagesGerees;
import metier.JeuVideo;
import static metier.JeuVideo.getNomsListeJeuxVideos;
import static metier.JeuVideo.listeJeuxVideosGeres;
import metier.Musique;
import static metier.Musique.getNomsListeMusiques;
import static metier.Musique.listeMusiquesGerees;
import metier.Oeuvre;
import static metier.Oeuvre.getNomsListeOeuvres;
import static metier.Oeuvre.listeOeuvresGerees;
import metier.TypeOeuvre;

/**
 *
 * @author jo
 */
public class RechercheOeuvre extends javax.swing.JDialog {

    /**
     * Creates new form RechercheOeuvre
     */
    public RechercheOeuvre()
    {
        tabNoms = TypeOeuvre.getTousLesTypes().toArray();
        tabNoms1 = CategorieFilm.getLesCategoriesPrincipalesDeFilms().toArray();
        tabNoms2 = CategorieMusiqueClip.getLesCategoriesPrincipalesDeClips().toArray();

        cBoxTypeOeuvreModele = new DefaultComboBoxModel(tabNoms);               //types d'oeuvres
        cBoxTypeOeuvreModele.setSelectedItem("Aucun");                          //selection par defaut du premier comboBox

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboxTypeOeuvre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel1.setText("Rechercher une Oeuvre");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Critères de recherche"));

        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Titre:");

        jLabel3.setText("Type:");

        jComboBox1.setModel(cBoxTypeOeuvreModele);
        jComboBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Catégorie:");

        jComboBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Saisir un titre d'oeuvre OU selectionner un type ainsi qu'une catégorie:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(342, 342, 342)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        cboxTypeOeuvre.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), "Liste des oeuvres trouvées"));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Retour");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Afficher l'oeuvre");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Ajouter à une séance publique");
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("oeuvres trouvées");

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(cBoxModeleVide);
        jComboBox3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cboxTypeOeuvreLayout = new javax.swing.GroupLayout(cboxTypeOeuvre);
        cboxTypeOeuvre.setLayout(cboxTypeOeuvreLayout);
        cboxTypeOeuvreLayout.setHorizontalGroup(
            cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cboxTypeOeuvreLayout.createSequentialGroup()
                .addGroup(cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(19, 19, 19))
        );
        cboxTypeOeuvreLayout.setVerticalGroup(
            cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(cboxTypeOeuvreLayout.createSequentialGroup()
                        .addGroup(cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(cboxTypeOeuvreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(339, 339, 339))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxTypeOeuvre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cboxTypeOeuvre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        //bouton recherche
        int i = 0;                                              //nombre de résultats

        lesOeuvresTrouvees = new ArrayList();
        lesImagesTrouvees = new ArrayList();
        lesEcritsTrouves = new ArrayList();
        lesMusiquesTrouvees = new ArrayList();
        lesClipsTrouves = new ArrayList();
        lesFilmsTrouves = new ArrayList();
        lesJeuxVideosTrouves = new ArrayList();

        Iterator<Oeuvre> iter = listeOeuvresGerees.iterator();

        jTextArea1.setText("");                                 //textArea vidée à chaque recherche

        if (jComboBox1.getSelectedIndex() == 6)                  //"Aucun" selectionné => uniquement titre saisi => recherche parmi toutes les oeuvres
        {
            Oeuvre o;
            
            if (jTextField1.getText().equals(""))                //si aucun titre n'est saisi, on retourne toute la liste
            {
                lesOeuvresTrouvees = listeOeuvresGerees;
            } 
            else                                                 //sinon, parcour de la liste d'oeuvres
            {
                while (iter.hasNext())
                {
                    if ((o = iter.next()).getNomOeuvre().contains(jTextField1.getText().toUpperCase()))
                    {
                        lesOeuvresTrouvees.add(o);
                    }
                }
            }
            i = lesOeuvresTrouvees.size();                       //nombre d'oeuvres trouvées

            cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeOeuvres(lesOeuvresTrouvees).toArray());

        } 
        else                                                     //si comboBox  selectionnés
        {
            if (jComboBox1.getSelectedIndex() == 0)                      //si type Image selectionné
            {
                lesImagesTrouvees = listeImagesGerees;
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeImages(lesImagesTrouvees).toArray());
                i = lesImagesTrouvees.size();
            }

            if (jComboBox1.getSelectedIndex() == 1)                      //si type Ecrit selectionné
            {
                lesEcritsTrouves = listeEcritsGeres;
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeEcrits(lesEcritsTrouves).toArray());
                i = lesEcritsTrouves.size();
            }

            if (jComboBox1.getSelectedIndex() == 2)                      //si type Musique selectionné
            {
                lesMusiquesTrouvees = listeMusiquesGerees;
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeMusiques(lesMusiquesTrouvees).toArray());
                i = lesMusiquesTrouvees.size();
            }

            if (jComboBox1.getSelectedIndex() == 3)                      //si type Clip Video selectionné
            {
                for(ClipVideo c: listeClipsGeres)
                {
                    String catClipSelectionne = (String) jComboBox2.getSelectedItem();
                    String catClipTrouve = c.getCategoriePrincipaleMusique().getNomCategorieClipMusique();
                    
                    if (catClipSelectionne.equals(catClipTrouve))
                        lesClipsTrouves.add(c);
                }
                
                jTextArea1.setText(lesClipsTrouves.toString());
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeClips(lesClipsTrouves).toArray());
                i = lesClipsTrouves.size();
            }

            if (jComboBox1.getSelectedIndex() == 4)                      //si type Film selectionné
            {
                for(Film f: listeFilmsGeres)
                {
                    String catFilmSelectionne = (String) jComboBox2.getSelectedItem();
                    String catFilmTrouve = f.getCategoriePrincipaleDuFilm().getNomCategorieFilm();

                    if (catFilmSelectionne.equals(catFilmTrouve) == true)
                        lesFilmsTrouves.add(f);
                }
                jTextArea1.setText(lesFilmsTrouves.toString());
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeFilms(lesFilmsTrouves).toArray());
                i = lesFilmsTrouves.size();
            }

            if (jComboBox1.getSelectedIndex() == 5)                      //si type Jeu Video selectionné
            {
                lesJeuxVideosTrouves = listeJeuxVideosGeres;
                cBoxOeuvresTrouvees = new DefaultComboBoxModel(getNomsListeJeuxVideos(lesJeuxVideosTrouves).toArray());
                i = lesJeuxVideosTrouves.size();
            }

            jTextField2.setText(String.valueOf(i));

            if (i == 0)
            {
                jTextArea1.setText("Aucune oeuvre trouvée");
                jComboBox3.setModel(cBoxModeleVide);
            }
        }

        if (i == 0)
        {
            jTextArea1.setText("Aucune oeuvre trouvée");
        }

        jComboBox3.setModel(cBoxOeuvresTrouvees);
        jTextField2.setText(String.valueOf(i));

        if (i != 0)
            jComboBox3.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed
        //Affiche le bon "comboBox" en fontion de la categorie d'oeuvre selectionnée
        if (jComboBox1.getSelectedIndex() == 4)                  //si "film" selectionné
        {
            cBoxCategorieModele = new DefaultComboBoxModel(tabNoms1);
            jComboBox2.setModel(cBoxCategorieModele);
            jComboBox2.setVisible(true);
        } 
        else if (jComboBox1.getSelectedIndex() == 3)             //si clip video selectionné
        {
            cBoxCategorieModele = new DefaultComboBoxModel(tabNoms2);
            jComboBox2.setModel(cBoxCategorieModele);
            jComboBox2.setVisible(true);
        }

        if (!(jComboBox1.getSelectedIndex() == 6))               //si un type d'oeuvre est selectionné, => desactive le textfield + vide textfield
        {
            jTextField1.setText("");                                //vide le champ
            jTextField1.setEditable(false);                         //desactive le textfield
            jComboBox2.setEnabled(true);
        } else
        {
            jTextField1.setEditable(true);
            jComboBox2.setModel(cBoxModeleVide);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        for (Oeuvre o : listeOeuvresGerees)
        {
            if (o.getNomOeuvre().equals((String)jComboBox3.getSelectedItem()))
            {
                AffichageOeuvre affichage = new AffichageOeuvre(o);
                affichage.pack();
                affichage.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox2ActionPerformed
    {//GEN-HEADEREND:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        if (jTextField1.getText().length() != 0)           //si un caractere a été tapé dans le champ titre, on bloque les combobox
        {
            jComboBox1.setEnabled(false);
            jComboBox2.setEnabled(false);
        } else
        {
            jComboBox1.setEnabled(true);
            jComboBox2.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        String src = "Fonctionnalité en cours de développement";
        JOptionPane.showMessageDialog(this,src, "ERREUR",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
    {//GEN-HEADEREND:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox3ActionPerformed
    {//GEN-HEADEREND:event_jComboBox3ActionPerformed
        for (Oeuvre o : listeOeuvresGerees)
        {
            if (o.getNomOeuvre().equals(jComboBox3.getSelectedItem()))
            {
                jTextArea1.setText(o.toString());
                break;
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RechercheOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RechercheOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RechercheOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RechercheOeuvre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                RechercheOeuvre dialog = new RechercheOeuvre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    private List<Oeuvre> lesOeuvresTrouvees;
    private List<Image> lesImagesTrouvees;
    private List<Ecrit> lesEcritsTrouves;
    private List<Musique> lesMusiquesTrouvees;
    private List<ClipVideo> lesClipsTrouves;
    private List<Film> lesFilmsTrouves;
    private List<JeuVideo> lesJeuxVideosTrouves;

    private Object[] tabNoms;
    private Object[] tabNoms1;
    private Object[] tabNoms2;

    private ComboBoxModel<String> cBoxTypeOeuvreModele;             //les types d'oeuvre
    private ComboBoxModel<String> cBoxCategorieModele;              //les catégories
    private ComboBoxModel<String> cBoxOeuvresTrouvees;
    private final ComboBoxModel<String> cBoxModeleVide = new DefaultComboBoxModel<String>();                   //vide pour les cas non traités

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel cboxTypeOeuvre;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton5;
    javax.swing.JComboBox<String> jComboBox1;
    javax.swing.JComboBox<String> jComboBox2;
    javax.swing.JComboBox<String> jComboBox3;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JTextField jTextField1;
    javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
